name: Torrent Seeder

on:
  workflow_dispatch:
    inputs:
      magnet:
        description: 'Magnet Link'     
        required: true
      trackers:
        description: 'Torrent Trackers'     
        required: false
        default: udp://tracker.opentrackr.org:1337/announce,udp://opentracker.i2p.rocks:6969/announce,https://opentracker.i2p.rocks:443/announce,udp://tracker.openbittorrent.com:6969/announce,udp://open.demonii.com:1337/announce,http://tracker.openbittorrent.com:80/announce,udp://9.rarbg.com:2810/announce,udp://open.tracker.cl:1337/announce,udp://exodus.desync.com:6969/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.moeking.me:6969/announce,udp://tracker1.bt.moack.co.kr:80/announce,https://tracker.tamersunion.org:443/announce,udp://tracker.bitsearch.to:1337/announce,udp://tracker.altrosky.nl:6969/announce,udp://tracker-udp.gbitt.info:80/announce,udp://movies.zsw.ca:6969/announce,https://tracker.gbitt.info:443/announce,http://tracker.gbitt.info:80/announce
      log-level:
        description: 'Log Level'  
        type: choice
        default: warn
        required: true
        options:
          - debug
          - info
          - notice
          - warn
          - error

jobs:
  seeder:
    runs-on: ubuntu-latest
    steps:
      - name: Install aria2c
        run: |
          sudo snap install aria2c
          sleep 10s
          echo
          
      - name: Start downloading
        run: |
          curl -sOL https://github.com/P3TERX/aria2.conf/raw/master/dht.dat
          curl -sOL https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat
          
          sudo aria2c \
            --log=- \
            --log-level=${{ inputs.log-level }} \
            --file-allocation=falloc \
            --listen-port=51413 \
            --dht-listen-port=51413 \
            --dht-entry-point=dht.transmissionbt.com:6881 \
            --dht-entry-point6=dht.transmissionbt.com:6881 \
            --dht-file-path=dht.dat \
            --dht-file-path6=dht6.dat \
            --enable-dht=true \
            --enable-dht6=false \
            --async-dns=true \
            --async-dns-server=1.0.0.1,1.1.1.1 \
            --seed-ratio=0.0 --bt-tracker="${{ inputs.trackers }}" "${{ inputs.magnet }}"
            
