name: Torrent Seeder

on:
  workflow_dispatch:
    inputs:
      magnet:
        description: 'Magnet Link'     
        required: true
      trackers:
        description: 'Trackers List'     
        required: false
      log-level:
        description: 'Log Level'  
        type: choice
        default: warn
        required: true
        options:
          - debug
          - info
          - notice
          - warn
          - error

jobs:
  seeder:
    runs-on: ubuntu-latest
    steps:
      - name: Install aria2c
        run: |
          sudo snap install aria2c
          sleep 10s
          echo
          
      - name: Start downloading
        run: |
          curl -sOL https://github.com/P3TERX/aria2.conf/raw/master/dht.dat
          curl -sOL https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat
          
          sudo aria2c \
            --log=- \
            --log-level=${{ inputs.log-level }} \
            --file-allocation=falloc \
            --listen-port=51413 \
            --dht-listen-port=51413 \
            --dht-entry-point=dht.transmissionbt.com:6881 \
            --dht-entry-point6=dht.transmissionbt.com:6881 \
            --dht-file-path=dht.dat \
            --dht-file-path6=dht6.dat \
            --enable-dht=true \
            --enable-dht6=true \
            --enable-peer-exchange=true \
            --async-dns=true \
            --async-dns-server=1.0.0.1,1.1.1.1 \
            --bt-enable-lpd=true \
            --bt-save-metadata=true
            --bt-load-saved-metadata=true
            --bt-tracker="${{ inputs.trackers }}"
            --seed-ratio=0.0 "${{ inputs.magnet }}"
            
